#!/bin/bash

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
#zsh theme
ZSH_THEME="ys"
# init oh my zsh
source $ZSH/oh-my-zsh.sh

################################################################################
## some env configuration
################################################################################

# init fasd for directory jump at cli
eval "$(fasd --init auto)"

# only run when no HHKB
# if this machine doesn't connect HHKB keyboard, we swap ctrl and caps.
if [[ "$(lsusb | grep HHKB)" == "" ]]; then
    setxkbmap -layout us -option ctrl:nocaps
fi

# only run at Ubuntu
if [[ "$(uname -a | grep Ubuntu)" == "" ]]; then
    # disable open a window when auto mount in ubuntu
    gsettings set org.gnome.desktop.media-handling automount-open false
fi

. ~/.thief.path.sh
