# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# theme
ZSH_THEME="ys"

DISABLE_AUTO_UPDATE="true"

# plugins
plugins=(
	fzf
    git
    history-substring-search
    colored-man-pages
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# for jump directory
eval "$(fasd --init auto)"

# import local path variables
if [ -f ${HOME}/.thief_path.sh ]; then
    . ${HOME}/.thief_path.sh
fi
if [ -f ${THIEF_HOME_PATH}/alias/alias.sh ]; then
    . ${THIEF_HOME_PATH}/alias/alias.sh
fi
if [ -f ${THIEF_HOME_PATH}/config/config.sh ]; then
    . ${THIEF_HOME_PATH}/config/config.sh
fi

# only run when no HHKB and not MacOS
# if this machine doesn't connect HHKB keyboard, we swap ctrl and caps.
is_ubuntu=$(uname -a | grep Ubuntu)
is_mac=$(uname -a | grep Darwin)
hhkb_result=$(lsusb 2>&1)
if [[ ! "${hhkb_result}" =~ "unable" ]]; then
	if [[ "$(echo ${hhkb_result} | grep HHKB )" == "" ]] && [[ "${is_mac}" == "" ]] ; then
       setxkbmap -layout us -option ctrl:nocaps
   fi
fi

# only run at Ubuntu
if [[ !  "${is_ubuntu}" == "" ]]; then
    # disable open a window when auto mount in ubuntu
    gsettings set org.gnome.desktop.media-handling automount-open false 2> /dev/null
fi
